export const allTypes = [
    { enType: 'normal', zhType: '一般', bgColor: '#A8A878' },
    { enType: 'fighting', zhType: '格鬥', bgColor: '#C03028' },
    { enType: 'flying', zhType: '飛行', bgColor: '#A890F0' },
    { enType: 'poison', zhType: '毒', bgColor: '#A040A0' },
    { enType: 'ground', zhType: '地面', bgColor: '#E0C068' },
    { enType: 'rock', zhType: '岩石', bgColor: '#B8A038' },
    { enType: 'bug', zhType: '蟲', bgColor: '#A8B820' },
    { enType: 'ghost', zhType: '幽靈', bgColor: '#705898' },
    { enType: 'steel', zhType: '鋼', bgColor: '#B8B8D0' },
    { enType: 'fire', zhType: '火', bgColor: '#F08030' },
    { enType: 'water', zhType: '水', bgColor: '#6890F0' },
    { enType: 'grass', zhType: '草', bgColor: '#78C850' },
    { enType: 'electric', zhType: '電', bgColor: '#F8D030' },
    { enType: 'psychic', zhType: '超能力', bgColor: '#F85888' },
    { enType: 'ice', zhType: '冰', bgColor: '#98D8D8' },
    { enType: 'dragon', zhType: '龍', bgColor: '#7038F8' },
    { enType: 'dark', zhType: '惡', bgColor: '#705848' },
    { enType: 'fairy', zhType: '妖精', bgColor: '#EE99AC' },
]