export const allTypes = [
    { english: 'normal', zh: '一般', },
    { english: 'fighting', zh: '格鬥', },
    { english: 'flying', zh: '飛行', },
    { english: 'poison', zh: '毒', },
    { english: 'ground', zh: '地面', },
    { english: 'rock', zh: '岩石', },
    { english: 'bug', zh: '蟲', },
    { english: 'ghost', zh: '幽靈', },
    { english: 'steel', zh: '鋼', },
    { english: 'fire', zh: '火', },
    { english: 'water', zh: '水', },
    { english: 'grass', zh: '草', },
    { english: 'electric', zh: '電', },
    { english: 'psychic', zh: '超能力', },
    { english: 'ice', zh: '冰', },
    { english: 'dragon', zh: '龍', },
    { english: 'dark', zh: '惡', },
    { english: 'fairy', zh: '妖精', },
]