export const allTypes = [
    { enType: 'normal', zhType: '一般', bgColor: '#A8A878' },
    { enType: 'fighting', zhType: '格鬥', bgColor: '#C03028' },
    { enType: 'flying', zhType: '飛行', bgColor: '#A890F0' },
    { enType: 'poison', zhType: '毒', bgColor: '#A040A0' },
    { enType: 'ground', zhType: '地面', bgColor: '#E0C068' },
    { enType: 'rock', zhType: '岩石', bgColor: '#B8A038' },
    { enType: 'bug', zhType: '蟲', bgColor: '#A8B820' },
    { enType: 'ghost', zhType: '幽靈', bgColor: '#705898' },
    { enType: 'steel', zhType: '鋼', bgColor: '#B8B8D0' },
    { enType: 'fire', zhType: '火', bgColor: '#F08030' },
    { enType: 'water', zhType: '水', bgColor: '#6890F0' },
    { enType: 'grass', zhType: '草', bgColor: '#78C850' },
    { enType: 'electric', zhType: '電', bgColor: '#F8D030' },
    { enType: 'psychic', zhType: '超能力', bgColor: '#F85888' },
    { enType: 'ice', zhType: '冰', bgColor: '#98D8D8' },
    { enType: 'dragon', zhType: '龍', bgColor: '#7038F8' },
    { enType: 'dark', zhType: '惡', bgColor: '#705848' },
    { enType: 'fairy', zhType: '妖精', bgColor: '#EE99AC' },
]

export const allGenerations = [
    { id: 1, zhName: '第一世代', zhRegion: '關都', },
    { id: 2, zhName: '第二世代', zhRegion: '成都', },
    { id: 3, zhName: '第三世代', zhRegion: '豐緣', },
    { id: 4, zhName: '第四世代', zhRegion: '神奧', },
    { id: 5, zhName: '第五世代', zhRegion: '合眾', },
    { id: 6, zhName: '第六世代', zhRegion: '卡洛斯', },
    { id: 7, zhName: '第七世代', zhRegion: '阿羅拉', },
    { id: 8, zhName: '第八世代', zhRegion: '伽勒爾', },
    { id: 9, zhName: '第九世代', zhRegion: '帕底亞', },
]